branches:
  only:
  - master
env:
  global:
    - DOCKER_CLIENT_TIMEOUT="120"
    - COMPOSE_HTTP_TIMEOUT="120"
    - UID="2000"
    - BASE_IMAGE_HASH="5f99e57"
services: 
- docker
push: &push
      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - |
          sudo add-apt-repository "$(echo "deb [arch=amd64] \
          	https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" \
          	| tr -d '\t')"
        - sudo apt-get update
        - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
        - docker version
        - echo $TRAVIS_BRANCH
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker images
        - |
          for i in `docker images --format {{.Repository}}:{{.Tag}}`; do
          	if [[ $TRAVIS_EVENT_TYPE == "push" ]]; then 
          		docker push $i;
          	fi
          done
alpine: &alpine
      stage: Build
      os: linux
      language: shell
      script:
        - docker-compose -f $COMPOSE_FILE build
        - docker system prune -f
        - docker rmi datajoint/djbase:py${PY_VER}-alpine-${BASE_IMAGE_HASH}
        - IMAGE=$(docker images | tail -1 | awk '{print $1}')
        - TAG=$(docker images | tail -1 | awk '{print $2}')
        - docker tag ${IMAGE}:${TAG} ${IMAGE}:${TAG}-${TRAVIS_COMMIT:0:7}
      <<: *push
debian: &debian
      stage: Build
      os: linux
      language: shell
      script:
        - docker-compose -f $COMPOSE_FILE build
        - docker system prune -f
        - docker rmi datajoint/djbase:py${PY_VER}-debian-${BASE_IMAGE_HASH}
        - IMAGE=$(docker images | tail -1 | awk '{print $1}')
        - TAG=$(docker images | tail -1 | awk '{print $2}')
        - docker tag ${IMAGE}:${TAG} ${IMAGE}:${TAG}-${TRAVIS_COMMIT:0:7}
        - |
          [ "$PY_VER" == "3.8" ] && docker tag ${IMAGE}:${TAG} ${IMAGE}:latest || echo
      <<: *push
jobs:
  include:
    - <<: *alpine
      env:
      - LABEL: alpine
      - PY_VER: 3.8
      - COMPOSE_FILE: dist/alpine/docker-compose.yml
    - <<: *alpine
      env:
      - LABEL: alpine
      - PY_VER: 3.7
      - COMPOSE_FILE: dist/alpine/docker-compose.yml
    - <<: *alpine
      env:
      - LABEL: alpine
      - PY_VER: 3.6
      - COMPOSE_FILE: dist/alpine/docker-compose.yml
    - <<: *debian
      env:
      - LABEL: debian
      - PY_VER: 3.8
      - COMPOSE_FILE: dist/debian/docker-compose.yml
    - <<: *debian
      env:
      - LABEL: debian
      - PY_VER: 3.7
      - COMPOSE_FILE: dist/debian/docker-compose.yml
    - <<: *debian
      env:
      - LABEL: debian
      - PY_VER: 3.6
      - COMPOSE_FILE: dist/debian/docker-compose.yml
